=== kazuhikoarase/simcir/simcironline/src/flash/simcir.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema targetNamespace="http://www.d-project.com/simcir/2012"
		elementFormDefault="qualified" 
		attributeFormDefault="unqualified"
		xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:simcir="http://www.d-project.com/simcir/2012">

	<element name="simcir" type="simcir:SimcirType" />

	<complexType name="DeviceType">
		<sequence>
			<element name="param" type="simcir:ParamType" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" type="ID" />
		<attribute name="x" type="int" />
		<attribute name="y" type="int" />
		<attribute name="factory" type="string" />
		<attribute name="type" type="string" />
		<attribute name="label" type="string" />
	</complexType>

	<complexType name="SimcirType">
		<sequence>
			<element name="device" type="simcir:DeviceType" minOccurs="0" maxOccurs="unbounded" />
			<element name="connector" type="simcir:ConnectorType" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="title" type="string" />
	</complexType>

	<complexType name="ConnectorType">
		<attribute name="in" type="string" use="required" />
		<attribute name="out" type="string" use="required" />
	</complexType>

	<complexType name="ParamType">
        <attribute name="name" type="string" />
        <attribute name="value" type="string" />	</complexType>

</schema>

=== kazuhikoarase/simcir/trunk/simcironline/src/flash/BasicSet.xml
<?xml version="1.0" encoding="UTF-8" ?>
<simcir
	xmlns="http://www.d-project.com/simcir/2012"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.d-project.com/simcir/2012 simcir.xsd">

	<device label="In" type="In" />
	<device label="Out" type="Out" />

	<device label="DC" factory="BasicSet.swf" type="DC" />
	<device label="OSC" factory="BasicSet.swf" type="OSC" />

	<device label="PushOn" factory="BasicSet.swf" type="PushOn" />
	<device label="PushOff" factory="BasicSet.swf" type="PushOff" />
	<device label="Toggle" factory="BasicSet.swf" type="Toggle" />

	<device label="LED" factory="BasicSet.swf" type="LED" />

	<device label="BUF" factory="BasicSet.swf" type="BUF" />
	<device label="NOT" factory="BasicSet.swf" type="NOT" />
	<device label="AND" factory="BasicSet.swf" type="AND" />
	<device label="NAND" factory="BasicSet.swf" type="NAND" />

	<device label="NAND" factory="BasicSet.swf" type="NAND">
		<param name="numInputs" value="3"/>
	</device>

	<device label="OR" factory="BasicSet.swf" type="OR" />
	<device label="NOR" factory="BasicSet.swf" type="NOR" />
	<device label="EOR" factory="BasicSet.swf" type="EOR" />
	<device label="ENOR" factory="BasicSet.swf" type="ENOR" />

</simcir>
